### ISSUE TITLE
Running setup -k multiple times dumps environment

### ISSUE THREAD

**Issue by kfindeisen** [natelust/reups#9]
Attempting to run `rsetup -k` on a product that has already been set up (using either `eups` or `reups`) causes the program to dump an alphabetical list of all currently defined environment variables. This bug happens with both `-r` and default setup modes.

I can't determine whether the dump is in addition to or instead of setting up the product.

**Comment by natelust** [comment]
This is fixed in commit 1236b0d, which should make it into a new release soon.
